
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - TEST_GUILD_ID=${TEST_GUILD_ID}
      - OWNER_ID=${OWNER_ID}
      - BOT_PREFIX=.v
      - USE_GLOBAL=${USE_GLOBAL}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src

volumes:
  redis_data: